### ISSUE TITLE
Error: EBADF: bad file descriptor, close

### ISSUE THREAD

**Issue by christianbundy** [pull-stream/pull-file#6]
It looks like we're having some issue with our file descriptor? See https://github.com/ssbc/multiblob/issues/11 for more info.

```
Error: EBADF: bad file descriptor, close
    at err (/home/christianbundy/src/ssbc/patchbay/node_modules/multiblob/index.js:38:23)
    at onNext (/home/christianbundy/src/ssbc/patchbay/node_modules/pull-catch/index.js:9:32)
    at /home/christianbundy/src/ssbc/patchbay/node_modules/pull-file/index.js:137:9
    at FSReqWrap.oncomplete (fs.js:135:15)
```

**Comment by dominictarr** [comment]
what actually causes this though? is it trying to close it twice? or is it opening a file that doesn't exist?

**Comment by christianbundy** [comment]
I'm not sure, I've never been able to pin down exactly when or why it's happening.

**Comment by christianbundy** [comment]
Here's a stack trace I just got (on the older multiblob):

```
Error: Error: EBADF: bad file descriptor, close
    at err (/home/christianbundy/src/flotilla/node_modules/multiblob/util.js:67:23)
    at onNext (/home/christianbundy/src/flotilla/node_modules/pull-catch/index.js:9:32)
    at /home/christianbundy/src/flotilla/node_modules/pull-file/index.js:137:9
    at /home/christianbundy/src/oasis/node_modules/graceful-fs/graceful-fs.js:57:14
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
```

Looks like now graceful-fs is involved.

**Comment by dominictarr** [comment]
where does graceful-fs get in there?

https://www.npmjs.com/package/graceful-fs#global-patching

> This should only ever be done at the top-level application layer, in order to delay on EMFILE errors from any fs-using dependencies. You should not do this in a library, because it can cause unexpected delays in other parts of the program.

looks like a bunch of things arn't following that advice: https://github.com/fraction/oasis/blob/master/yarn.lock#L2912 but as offended as I am by "graceful-fs"'s monkeypatching, we do see EBADF in other places.

I've been looking around to try and figure out what can cause an `EBADF`... I just see some threads were someone says to increase the `ulimit` and it maybe fixes it or doesn't.
It's not that the file doesn't exist because that would cause an `ENOENT`

**Comment by christianbundy** [comment]
Maybe I could decrease `ulimit` a bunch and see if I can repro? The trouble has mostly been the inconsistent reproduction, so I'll investigate for an hour, find nothing, and a month later I'll get a hundred of these errors in stdout.
